<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Deepikas-MacBook-Air.local" failures="1" tests="2" name="Default test(failed)" time="0.018" errors="0" timestamp="2024-08-05T16:36:44 PDT">
  <testcase classname="retryfailure.RetryFailedTest" name="test2" time="0.003"/>
  <testcase classname="retryfailure.RetryFailedTest" name="test3" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryfailure.RetryFailedTest.test3(RetryFailedTest.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="retryfailure.RetryFailedTest" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
  <testcase classname="retryfailure.RetryFailedTest" name="test4" time="0.0">
    <ignored/>
  </testcase> <!-- test4 -->
</testsuite> <!-- Default test(failed) -->
